# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13636ceb97cca3b8371b690659e5adc41367da558d65a47a4d620762c9b8d65ebd7f5e8099a8e33141d5fcf4db99abaad0072cec51124debb61cdf0d5a1bface

test:
  secret_key_base: 8179962b83bedd7f9bc687219dff32cd6d61071e009f1b34c75caacc08750cd6f8a2e9cba1066d735049f44ac35e183796fb28a7c84f031495263a327eb5c923

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
