class Api::ApplicationController < ApplicationController
  # This will stop rails from raising an error if
  # a post does not have an authenticity token.
  # Authenticity tokens are generated by rails to
  # let it identify post requests as being submitted
  # from its own forms.
  skip_before_action :verify_authenticity_token

=begin
fetch(
  'http://localhost:3000/api/v1/questions',
  {
    headers: {
      'Authorization' : 'd5c234ff7b9b6bb96e7a125b8f6755ae539eb7e6b0ebabfc4dffe26f021059e8'
    }
  }
)
=end

  def current_user
    @user ||= User.find_by(api_key: api_key) unless api_key.nil?
  end

  private
  def api_key
    if request.headers['AUTHORIZATION']&.length == 64
      request.headers['AUTHORIZATION']
    end
  end

  def authenticate_user!
    head :unauthorized unless current_user.present?
  end
end









##
